### ISSUE TITLE
Install problem - after installing on Splunk Cloud stack Error 500

### ISSUE THREAD

**Issue by kylexh1** [Bre77/SuperLogout#1]
I installed this on a Splunk Cloud 
Version:
9.0.2209.2
Classic stack and get 

500 Internal Server Error 

when going to the app.

**Comment by Bre77** [comment]
Hey @kylexh1 can you confirm your running version 1.0.0 of the app? I tested on Splunk Cloud 9.0.2209.2 Victoria with no issues. I'd also look at `index=_internal "super_logout"` for specific errors.

**Comment by Bre77** [comment]
Restarting the search head resolves this issue. Alternatively install the app via any other method other than the build in Splunkbase browser (SSAI).
